(fix) Add more explicit types for 'EventEmitter<T>'
This is required for Angular Angular 2.0.0-alpha.46 to remove compiler
errors like:
error TS2314: Generic type 'EventEmitter<T>' requires 1 type argument(s).

Relates #34